### ISSUE TITLE
https

### ISSUE THREAD

**Issue by kdabir** [robertaboukhalil/jqkungfu#1]
Currently https://www.jqkungfu.com doesn't work* 
Ideally, http://www.jqkungfu.com/ should redirect to https://www.jqkungfu.com/

*it works but gives warning on browsers
![image](https://user-images.githubusercontent.com/735240/58015064-ecdecf00-7b17-11e9-8b7a-44333d55c41a.png)

**Comment by robertaboukhalil** [comment]
Done!
