### ISSUE TITLE
usage with nodejs

### ISSUE THREAD

**Issue by travisghansen** [robertaboukhalil/jqkungfu#3]
This is really cool stuff. I'm currently writing a project in node where I'd like to heavily utilize `jq` but I've noticed the performance is pretty tough likely from all the `exec`ing etc going on (https://github.com/sanack/node-jq/issues/222).

Fundamentally (and forgive my ignorance) would this be any different than the above project?

**Comment by robertaboukhalil** [comment]
Interesting thought! My _guess_ would be that using jq via WebAssembly should be faster than creating a child process, but I haven't tested that. I'll look into this when I get a chance.

**Comment by travisghansen** [comment]
Cool, thanks!

**Comment by robertaboukhalil** [comment]
Sorry for the late reply! Following up on this, you should be able to modify `compile.sh` to make it Node.js-friendly by adding the `-s NODERAWFS` Emscripten flag to `emcc`, which will give the wasm module read/write access to your local filesystem. You can then run it by doing `node jq.js`. From there, you should be able to test out the performance.
