### ISSUE TITLE
JSON syntax error if more than one input or output

### ISSUE THREAD

**Issue by wader** [robertaboukhalil/jqkungfu#6]
Hi, noticed this when i was playing around:
![Screenshot 2023-02-07 at 20 31 23](https://user-images.githubusercontent.com/185566/217346551-f880afa4-89e3-4866-9694-d98211870d32.png)

**Comment by robertaboukhalil** [comment]
Hi @wader,

That's expected because the input isn't a valid JSON, so the editor shows a syntax error, but `jq` treats each row as separate entry, e.g. if you try `.+5`, the output will be `6 7`

**Comment by wader** [comment]
I see, was thinking it would be nice if even multiple JSON values could be highlighted as it's supported and a common (at least of me 😄) use case with jq

**Comment by robertaboukhalil** [comment]
That would be nice, not sure how to that with the ACE editor, but PRs are welcome :)

**Comment by wader** [comment]
Aha yeah maybe tricky, unfortunately have no experience with ACE highlighting so a bit work. Yeap will send a PR if i look into it. Feel free to close the issue if you like.

**Comment by robertaboukhalil** [comment]
Thanks!
