### ISSUE TITLE
Allow queries on mutliple lines

### ISSUE THREAD

**Issue by iainelder** [robertaboukhalil/jqkungfu#7]
I love that this tool allows me to interactively build JQ queries.

Some of my queries are quite complex and are readble only across multiple lines.

I can paste a multiline query easily enough, and it still works. But it all gets flattened out into an unreadable mess so I can't edit it in the tool.

**Comment by robertaboukhalil** [comment]
Thanks @iainelder! 

I've mostly stopped development on jqkungfu, but have moved the functionality to sandbox.bio. Can you try your multiline query at https://sandbox.bio/playgrounds?id=jq ? Under the "Examples" dropdown, check out the last 2 examples: "Rename Fields" or "Convert a TSV to JSON" for multiline queries.

Hopefully that does the trick.

**Comment by iainelder** [comment]
Hi, thanks, that's just the functionality I was looking for.

I like how the text area dynamically grows as I add more lines to the query.

I'll post my next question in the [feedback area](https://github.com/sandbox-bio/feedback/discussions) for sandbox.bio.

**Comment by robertaboukhalil** [comment]
Hey @iainelder, I just added a resizable textarea, hope this helps with your use case!

**Comment by iainelder** [comment]
It does the job nicely. Thanks!
